### PR TITLE
Better node container for gulp watcher

### PR DESCRIPTION
**Pull request by rpsu**
Change Node base image to the official Node container.

Watching docker-compose logs displays the process (both installation of `npm install` and the `gulp watch` when it starts watching and compiling.

### CODE REVIEW

**Comment by rpsu** [comment]
NOTE this is built on top of PR #156 
cc @kekkis

**Comment by kekkis** [comment]
Checked with @HeikkiYlipaavalniemi and he noted that anything below node version 12 should be compatible with the gulp version we're using internally in most projects.

**Comment by rpsu** [comment]
nodejs image is declared to "node:11", and tested to work with the base img in question, too

**Comment by rpsu** [comment]
I'll merge this now, let's resolve possible issues via issue queue.

**Pull request merged**
